// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zenora - Luz Interior, Essência Tranquila",
  description: "Guie sua jornada para reduzir ansiedade, melhorar o sono e equilibrar sua energia com práticas rápidas e acessíveis.",
  manifest: "/manifest.json",
  themeColor: "#4CB09A",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Zenora",
  },
  openGraph: {
    type: "website",
    title: "Zenora - Luz Interior, Essência Tranquila",
    description: "Guie sua jornada para reduzir ansiedade, melhorar o sono e equilibrar sua energia",
    siteName: "Zenora",
  },
  twitter: {
    card: "summary_large_image",
    title: "Zenora - Luz Interior, Essência Tranquila",
    description: "Guie sua jornada para reduzir ansiedade, melhorar o sono e equilibrar sua energia",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#4CB09A" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
